### ISSUE TITLE
Username disappear when going to Help page. 

### ISSUE THREAD

**Issue by Muhammad-Adam** [HappeNUS/happenus#27]

**Comment by ianngiaw** [comment]
Fixed this by adding a subscription to either allUserData or ownUserData to the waitOn of each route. Should find a way to make ownUserData persist on all pages instead of subscribing on all of the routes

**Comment by Muhammad-Adam** [comment]
Still cannot see username

**Comment by ianngiaw** [comment]
are you sure cause it is ok on both my end and on happenus-test
