### ISSUE TITLE
Card reveal should only be revealed one at a time to maintain neatness

### ISSUE THREAD

**Issue by Muhammad-Adam** [HappeNUS/happenus#38]

**Comment by ianngiaw** [comment]
If this is to be implemented, must ensure that it does not consume too many resources

**Comment by Muhammad-Adam** [comment]
Only added one click event to close previous reveal.

**Comment by ianngiaw** [comment]
Whats the point of closing the previous reveal

**Comment by Muhammad-Adam** [comment]
if u leave it open, it will be messy if u open up alot of cards. No pictures can be seen. if users click other reveals, their attention is already moved to the other event. so there is no need to leave the card revealed.

**Comment by ianngiaw** [comment]
nvm. closed.
